### ISSUE TITLE
b_frames_present incorrectly set.

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#12]
ffprobe -show_frames for t2 shows the b-frames are present.

**Comment by nicholas-fr** [comment]
Thanks for the feedback. 
I'm not sure what is causing this issue as I have been unable to reproduce it unfortunately.

I have added a debug feature to the script.
If you still see this or a similar issue with the latest version of the script, please  would you run the script with the `--debug` option, and share the tcval_logs_date_time.zip that is created, so that I can check how the script may be misinterpreting the ffmpeg/MP4Box logs.

**Comment by Lis-TV** [comment]
When I edit wave_12.5_25_50_test_results_2023-04-06_20-26-27.json

"TestStreamValidation": {
        "test_stream_id": "2",
        "test_file_path": "../dpctf-deploy/content/cfhd_sets/12.5_25_50/t2/2022-10-17",
....
        "b_frames_present": {
            "expected": true,
            "detected": false,
            "test_result": "fail"
        },

But when I run:
_cd ../dpctf-deploy/content/cfhd_sets/12.5_25_50/t2/2022-10-17/1/_
_cat init.mp4 > a.mp4_
_cat 0.m4s >> a.mp4_
_ffprobe -show_frames a.mp4 | grep pict_type_
...
pict_type=I
pict_type=B
pict_type=B
pict_type=P

**Comment by nicholas-fr** [comment]
Yes, unfortunately, when you're running the script, the parsing of the ffmpeg and/or MP4Box output appears to be going wrong. When running it in either Win10 or Linux I don't see this problem, and others who have run the scripts also haven't had this issue.

If you would please share the 3 JSON test_results files as well as the tcval_debug zip containing the ffmpeg/MP4Box output files created when including the `--debug` command. That should help me to figure out why the script is not returning the expected results. Thanks.

**Comment by Lis-TV** [comment]
After looking into the debug log I found that using -v with relative path 
_./tcval.py -v ../dpctf-deploy/content -m matrix_avc.csv --mezzanineversion 3_

generates ffmpeg error (cfhd_sets_12.5_25_50_t2_2022-10-17_trace_headers_init_2023-04-11_12-08-25.txt)
 
_../dpctf-deploy/content/cfhd_sets/12.5_25_50/t2/2022-10-17/stream.mpd: No such file or directory_


If I am using full path it works well.
_./tcval.py -v /home/krzysztof/dpctf-deploy/content -m matrix_avc.csv --mezzanineversion 3_

**Comment by gitwjr** [comment]
Fixed. An updated version needs to be posted. @nicholas-fr to address and close.
