### ISSUE TITLE
Usage of not existing folder

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#4]
line 387 and 380
The test_stream_path includes subfolder '\\1\\', which is not present in test stream vectors.
It should be for example:
test_stream_path = Path(str(test_stream_date_dir)+'\\'+TS_INIT_SEGMENT_NAME)

**Comment by nicholas-fr** [comment]
I believe this issue is due to outdated test vectors, that use an old folder/file structure, similar to issue #2.

Example of current test vector segment path:
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2022-07-20/1/

**Comment by nicholas-fr** [comment]
Thanks for raising this issue, I believe this has been explained/addressed. 
If you have further feedback, please feel free to reopen or create a new issue.
