### ISSUE TITLE
chunks per fragment incorrectly interpreted

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#5]
Row 9 description is "Fragments containing one or multiple moof/mdat pairs)", so to check that, the application need to read the number of moof/mdat pairs in output of the mp4box.

**Comment by nicholas-fr** [comment]
The script [reads](https://github.com/nicholas-fr/test-content-validation/blob/71c52293a4fcafc4f9ea8ae79a17261660223f02/tcval.py#L789) the number of samples from each TrackRunBox and so also knows the number of moof boxes (moof/traf/trun). It now also [reads](https://github.com/nicholas-fr/test-content-validation/blob/71c52293a4fcafc4f9ea8ae79a17261660223f02/tcval.py#L790) and [checks](https://github.com/nicholas-fr/test-content-validation/blob/71c52293a4fcafc4f9ea8ae79a17261660223f02/tcval.py#L805) there is an equal number of corresponding mdat boxes when determining a pass/fail.
This information is now reflected in the command line output, for example for cfhd_sets/15_30_60/t15:
"Chunks per fragment = moof=60 mdat=60 (multiple chunks per fragment, each chunk is one sample)"

**Comment by nicholas-fr** [comment]
Thanks for raising this issue, I believe this has been addressed. 
If you have further feedback, please feel free to reopen or create a new issue.
