### ISSUE TITLE
stream t34 broken detection

### ISSUE THREAD

**Issue by rbouqueau** [nicholas-fr/test-content-validation#8]
```framerate``` and ```cmaf_fragment_duration``` are detected as 0.

**Comment by rbouqueau** [comment]
Duration for 14.985 is also detected as 59s instead of 60s:

```
        "duration": {
            "expected": 60,
            "detected": 59,
            "test_result": "fail"
        }
```

**Comment by nicholas-fr** [comment]
Thanks! I found the issues and should have a fix by tomorrow.
I have `framerate` and `cmaf_fragment_duration` detection working. Just finalising the `duration` fix now.

It appears the VUI timing data for t34 12.5fps and 14.985fps may be invalid:
14.985fps:
`num_units_in_tick            00000000000000000000000000000001 = 1`
`time_scale                   00000000000000000111010100110000 = 30000`
15000fps?

12.5fps:
`num_units_in_tick            00000000000000000000000000000001 = 1`
`time_scale                   00000000000000000110010000000000 = 25600`
12800fps?

**Comment by rbouqueau** [comment]
Thanks. I've checked on the content I am uploading and 14.985fps is still incorrect:

29.97fps:
```
[trace_headers @ 0x56265a52d900] 130         timing_info_present_flag                                    1 = 1
[trace_headers @ 0x56265a52d900] 131         num_units_in_tick            00000000000000000000000000000001 = 1
[trace_headers @ 0x56265a52d900] 163         time_scale                   00000000000000001110101001100000 = 60000
[trace_headers @ 0x56265a52d900] 195         fixed_frame_rate_flag                                       0 = 0
```

It may come from the way the parameters are forward to libx264. I'm checking.

**Comment by rbouqueau** [comment]
> It may come from the way the parameters are forward to libx264. I'm checking.

I confirm

**Comment by rbouqueau** [comment]
I've made a local fix for this. I will fix it within the next few days.

**Comment by nicholas-fr** [comment]
Frame rate, duration and fragment duration issues should now be resolved with commit https://github.com/nicholas-fr/test-content-validation/commit/a8f64b3c9ff2855b8b8ef21c1ef7c4d97043ac94.

**Comment by rbouqueau** [comment]
I confirm.
