### ISSUE TITLE
pic_timing sei is not detected properly

### ISSUE THREAD

**Issue by rbouqueau** [nicholas-fr/test-content-validation#9]
We are looking for two timing information:
- The VUI timing info (which is mainly found in the SPS). This is different from ```pic_struct``` (also in the VUI) which is currently checked by the script.
- The PicTiming SEI. SEIs are conveyed as independent NALUs. If it can help, ```MP4Box -dxml``` dumps you the NALUs.

**Comment by nicholas-fr** [comment]
Thanks! The VUI timing info was detected (although its absence wasn't handled properly).
The pic_timing SEI presence was mistakenly linked to VUI pic_struct_present_flag = 1, not taking into account the other possible condition CpbDpbDelaysPresentFlag = 1. The script now just checks directly for the pic_timing SEI presence (as detected by ffmpeg).

Both issues should now be resolved with commit https://github.com/nicholas-fr/test-content-validation/commit/a8f64b3c9ff2855b8b8ef21c1ef7c4d97043ac94.

**Comment by rbouqueau** [comment]
I confirm.
